### ISSUE TITLE
Failed steps marked as completed

### ISSUE THREAD

**Issue by amalv** [itszero/wdio-browserstack-service#10]
I'm using browserstack, cucumber js and webdriverio for automation testing.

I changed a step in order to make it fail to see if an HTTP request was made to browserstack in indicating that the build had an error:

![failedstep](https://user-images.githubusercontent.com/1252707/29370579-13d36272-82a6-11e7-806f-addcdd1ab2fd.png)

However it seems that the HTTP request made marked the build as completed instead of error.

![markedviarestapi](https://user-images.githubusercontent.com/1252707/29370700-801009b8-82a6-11e7-9325-9b8573ea59a3.png)

So it seems that the service is working (since it marked the build completed via the HTTP REST API from Browserstack), however it fails to mark builds that have errors.

After debugging a little I think the cause of the error is the lack of support for Cucumber. Currently the service does not support the methods `beforeFeature`, `afterStep` and `beforeScenario`. After adding these methods to the `browserstack-service` under `lib` and building the project, I've been able to mark builds with errors.

I've created [this PR](https://github.com/itszero/wdio-browserstack-service/pull/11) in order to fix the problem.

**Comment by itszero** [comment]
Thanks for doing this! I left a small nit on the PR and a question. I would be happy to merge and release once it's resolved. 👍

**Comment by amalv** [comment]
Just a clarification about this issue: in order to fix the problem I took a look at [wdio-sauce-service](https://github.com/webdriverio/wdio-sauce-service/blob/master/lib/sauce-service.js) and then I implemented the methods related to Cucumber tests and adapt them a little in order to use browserstack context instead of saucelabs.

After that I implemented these methods in `wdio-browserstack-service`, then created a build and tried it against browserstack, and now when a step fails, the automated test is marked as errored via HTTP request to the Browserstack API.

**Comment by itszero** [comment]
Merged your PR. I'll publish a new version shortly.

**Comment by itszero** [comment]
0.1.12 released
