### ISSUE TITLE
wdio browserstack service not starting the local binary

### ISSUE THREAD

**Issue by biz786** [itszero/wdio-browserstack-service#20]
Hi i am using wdio config file to configure running tests on browserstack. I need to run the tests using the browserstack local binary since the servers im testing are not accessible from the outside world.But im getting error

ERROR: connect ETIMEOUT <someip:someport>

My wdio config:

![img_20180312_174459](https://user-images.githubusercontent.com/4602480/37311502-d4823a5a-261d-11e8-8655-d9bbbb08b1de.jpg)

Does the wdio browserstack service automatically download the local binary or do i have to do 

npm install browserstack-local

**Comment by itszero** [comment]
Closed due to the move into the webdriverio monorepo. Please reopen an issue there if you still have the issue. Thanks!
