### ISSUE TITLE
Browserstack Session Rest-API status always green when setting bail to true 

### ISSUE THREAD

**Issue by goatsy** [itszero/wdio-browserstack-service#24]
I have several tests in my spec-File.

Example below.

In my config-File I have set the mochaOpts parameter

`bail: true`

and also in the Webdriverio Config Parameter 

`bail: 1`

The first test fails, and the other tests are not executed (which is right) but on Browserstack API apparently "passed" is sent.
The session has the green tick https://www.browserstack.com/images/layout/sp-success.png

`describe('Bail Test', function () {
    
    it('description', function () {
        Page.open("www.google.de")
        expect(Page.getUrl).to.have.string("abcde");
    });
    
    it('description 2', function () {
        Page.open("www.google.de")
        expect(Page.getUrl).to.have.string("abcde");
    });

    it('description 3', function () {
        Page.open("www.google.de")
        expect(Page.getUrl).to.have.string("abcde");
    });`

Am I doing something wrong?

**Comment by abjerstedt** [comment]
I tracked this down to wdio triggering the AFTER() hook prior to the AFTERTEST() hook. In the event of a bail, the failure count will still be 0. I'm going to look into fixing this as part of v5.

**Comment by goatsy** [comment]
@abjerstedt 
Using the service with WebdriverIO v5 I only get "green" status for my Browserstack tests. No matter if the tests fail or pass. 

snippet of my config

```
   services: ['browserstack']
    bail: 0
```

**Comment by abjerstedt** [comment]
What is your package.json? This was fully fixed with our update to mocha v6.

**Comment by goatsy** [comment]
` "@wdio/allure-reporter": "^5.4.8",
        "@wdio/cli": "^5.4.8",
        "@wdio/dot-reporter": "^5.4.3",
        "@wdio/junit-reporter": "^5.4.8",
        "@wdio/local-runner": "^5.4.8",
        "@wdio/mocha-framework": "^5.4.8",
        "@wdio/selenium-standalone-service": "^5.2.2",
        "@wdio/spec-reporter": "^5.4.3",
        "@wdio/sync": "^5.4.6",
        "chai": "^4.2.0",
        "deepmerge": "^3.1.0",
        "dotenv": "^6.2.0",
        "eslint": "^5.12.1",
        "eslint-plugin-wdio": "^5.2.2",
        "jsdoc": "^3.5.5",
        "mkdirp": "^0.5.1",
        "ncp": "^2.0.0",
        "rimraf": "^2.6.2",
        "uuid": "^3.3.2",
        "wdio-browserstack-service": "^0.1.18",
        "yargs": "^12.0.4"`


My test itself on iOs fails because of a "An element could not be located on the page using the given search parameters."

But the Browserstack Session is still marked as green. 

When I check the Browserstack Session on the BS Dashboard I see the following 

`Get log types⇒WINDOW syslog WINDOW crashlog WINDOW performance
Get logs ⇒ Appium error: An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found.`


Maybe these errors lead to WebdriverIO not being able to marke the test correctly.

**Comment by itszero** [comment]
I'm going to close this issue as the package is now part of the webdriver.io monorepo. I think you'll be able to find more help over there!
