### ISSUE TITLE
Need to update sub-dependency to remove event-stream hacked module

### ISSUE THREAD

**Issue by paulbjensen** [itszero/wdio-browserstack-service#25]
Hi,

Just writing to note that one of this module's dependencies has the event-stream npm module as a dependency, which has been found to have a backdoor:

https://github.com/dominictarr/event-stream/issues/116

I will help to get that compromised module sorted out.

Regards,

Paul Jensen

**Comment by itszero** [comment]
Closed. Thanks for flagging! 0.1.17 is released for this.
