### ISSUE TITLE
Migrate upcoming fixes to the v5 repo.

### ISSUE THREAD

**Issue by abjerstedt** [itszero/wdio-browserstack-service#29]
I've ported Last week's version of this service to the v5 monorepo as of this morning (and published as of 5.0.0-beta.12). Lets try to keep upcoming changes moving forward to the new package.

**Comment by itszero** [comment]
Sorry that I missed the message. Actually I'll be happy to archive this repo and redirect people to the new monorepo since I'm not actively using webdriver.io anymore.

Thanks for merging it into the monorepo!
