### ISSUE TITLE
Is it possible to output a link to the session in Browserstack?

### ISSUE THREAD

**Issue by tylerbrandt** [itszero/wdio-browserstack-service#5]
Hi,

This is more of a feature/documentation request. I've been using this plugin for a while and it works great, thanks! However, I was wondering if it was possible to report the Browserstack job URL in the log, so that we can easily click from a test run to the Browserstack session. For example, [`karma-browserstack-launcher`](https://github.com/karma-runner/karma-browserstack-launcher) outputs the job URL when instantiating the session, and it is pretty helpful when we need to dig into the logs:

![client-js-xbrowser__694_console__jenkins_](https://cloud.githubusercontent.com/assets/1256483/26365554/cbe3da10-3f9c-11e7-907b-c46a526963cc.png)

As it is I just set a unique Browserstack "project" per job and so I can find it, but a link would simplify this workflow considerably.

Apologies if this is already supported, and I just missed it! Thanks.

**Comment by itszero** [comment]
Sorry I was on vacation, it looks like it might be possible. I'll look into it.
